// AUTO-GENERATED by scripts/generate-app-identity.ts
// Source: config/universal.toml [app] + [app.compat]
// Do not edit manually.

export const APP_ID = "work" as const;
export const APP_NAME = "Work" as const;
export const APP_NAMESPACE = "work" as const;
export const APP_ENV_PREFIX = "WORK" as const;

export const APP_LEGACY_IDS = ["atlassian"] as const;
export const APP_ENV_PREFIX_ALIASES = ["ATLASSIAN"] as const;
export const APP_ENV_PREFIXES = ["WORK","ATLASSIAN"] as const;

export const ROUTE_HINT_PRIMARY_KEY = "__workRoute" as const;
export const ROUTE_HINT_WINDOW_KEYS = ["__workRoute","__atlassianRoute"] as const;

export const WEBVIEW_PRIMARY_MARKER = "work-webview" as const;
export const WEBVIEW_MARKERS = ["work-webview","atlassian-webview"] as const;

export const buildEnvKeys = (suffix: string, extras: readonly string[] = []): string[] => {
  const clean = suffix.replace(/^_+/, "");
  return [...APP_ENV_PREFIXES.map((prefix) => `${prefix}_${clean}`), ...extras];
};

export const buildViteEnvKeys = (suffix: string): string[] =>
  buildEnvKeys(suffix).map((key) => `VITE_${key}`);

export const firstEnvValue = (
  env: Record<string, string | undefined>,
  keys: readonly string[],
): string => {
  for (const key of keys) {
    const value = env[key];
    if (typeof value === "string" && value.trim()) {
      return value;
    }
  }
  return "";
};
