/**
 * Generates `src/shared/app-identity.ts` from `config/universal.toml`.
 *
 * This keeps app identity (id/name/prefix + legacy aliases) centralized and
 * prevents drift across extension host, webview, and dev scripts.
 */
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const ROOT = resolve(import.meta.dir, "..");
const CONFIG_PATH = resolve(ROOT, "config/universal.toml");
const OUT_PATH = resolve(ROOT, "src/shared/app-identity.ts");

const toml = readFileSync(CONFIG_PATH, "utf8");

function getSection(name: string): string {
  const escaped = name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const match = toml.match(new RegExp(`\\[${escaped}\\]\\n([\\s\\S]*?)(?=\\n\\[|$)`));
  return match?.[1] ?? "";
}

function readString(section: string, key: string, fallback: string): string {
  const escaped = key.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return section.match(new RegExp(`${escaped}\\s*=\\s*"([^"]+)"`))?.[1] ?? fallback;
}

function readStringArray(section: string, key: string, fallback: string[]): string[] {
  const escaped = key.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const raw = section.match(new RegExp(`${escaped}\\s*=\\s*\\[([^\\]]*)\\]`))?.[1];
  if (!raw) {
    return fallback;
  }
  const values = [...raw.matchAll(/"([^"]+)"/g)].map((m) => m[1].trim()).filter(Boolean);
  return values.length > 0 ? values : fallback;
}

const appSection = getSection("app");
const compatSection = getSection("app.compat");

const appId = readString(appSection, "id", "work");
const appName = readString(appSection, "name", "Work");
const appNamespace = readString(appSection, "namespace", appId);
const appEnvPrefix = appId.replace(/[^a-zA-Z0-9]/g, "_").toUpperCase();

const legacyIds = readStringArray(compatSection, "legacyIds", ["atlassian"]);
const legacyEnvPrefixes = readStringArray(compatSection, "legacyEnvPrefixes", ["ATLASSIAN"]);
const legacyRouteHintKeys = readStringArray(compatSection, "legacyRouteHintKeys", ["__atlassianRoute"]);
const legacyWebviewMarkers = readStringArray(compatSection, "legacyWebviewMarkers", ["atlassian-webview"]);

const routeHintPrimaryKey = `__${appId}Route`;
const webviewPrimaryMarker = `${appId}-webview`;

const unique = (values: string[]) => [...new Set(values)];
const envPrefixes = unique([appEnvPrefix, ...legacyEnvPrefixes]);
const routeHintKeys = unique([routeHintPrimaryKey, ...legacyRouteHintKeys]);
const webviewMarkers = unique([webviewPrimaryMarker, ...legacyWebviewMarkers]);

const file = `// AUTO-GENERATED by scripts/generate-app-identity.ts
// Source: config/universal.toml [app] + [app.compat]
// Do not edit manually.

export const APP_ID = ${JSON.stringify(appId)} as const;
export const APP_NAME = ${JSON.stringify(appName)} as const;
export const APP_NAMESPACE = ${JSON.stringify(appNamespace)} as const;
export const APP_ENV_PREFIX = ${JSON.stringify(appEnvPrefix)} as const;

export const APP_LEGACY_IDS = ${JSON.stringify(legacyIds)} as const;
export const APP_ENV_PREFIX_ALIASES = ${JSON.stringify(legacyEnvPrefixes)} as const;
export const APP_ENV_PREFIXES = ${JSON.stringify(envPrefixes)} as const;

export const ROUTE_HINT_PRIMARY_KEY = ${JSON.stringify(routeHintPrimaryKey)} as const;
export const ROUTE_HINT_WINDOW_KEYS = ${JSON.stringify(routeHintKeys)} as const;

export const WEBVIEW_PRIMARY_MARKER = ${JSON.stringify(webviewPrimaryMarker)} as const;
export const WEBVIEW_MARKERS = ${JSON.stringify(webviewMarkers)} as const;

export const buildEnvKeys = (suffix: string, extras: readonly string[] = []): string[] => {
  const clean = suffix.replace(/^_+/, "");
  return [...APP_ENV_PREFIXES.map((prefix) => \`\${prefix}_\${clean}\`), ...extras];
};

export const buildViteEnvKeys = (suffix: string): string[] =>
  buildEnvKeys(suffix).map((key) => \`VITE_\${key}\`);

export const firstEnvValue = (
  env: Record<string, string | undefined>,
  keys: readonly string[],
): string => {
  for (const key of keys) {
    const value = env[key];
    if (typeof value === "string" && value.trim()) {
      return value;
    }
  }
  return "";
};
`;

await Bun.write(OUT_PATH, file);
console.log(`Wrote ${OUT_PATH}`);
