/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkIndexRouteImport } from './routes/work/index'
import { Route as SystemIndexRouteImport } from './routes/system/index'
import { Route as ShipIndexRouteImport } from './routes/ship/index'
import { Route as ReviewIndexRouteImport } from './routes/review/index'
import { Route as PlanIndexRouteImport } from './routes/plan/index'
import { Route as ObserveIndexRouteImport } from './routes/observe/index'
import { Route as NowIndexRouteImport } from './routes/now/index'
import { Route as ExecuteIndexRouteImport } from './routes/execute/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as SystemSettingsRouteImport } from './routes/system/settings'
import { Route as SystemRegistryRouteImport } from './routes/system/registry'
import { Route as SystemDocsRouteImport } from './routes/system/docs'
import { Route as PlanWeeklyRouteImport } from './routes/plan/weekly'
import { Route as PlanQuarterlyRouteImport } from './routes/plan/quarterly'
import { Route as PlanMonthlyRouteImport } from './routes/plan/monthly'
import { Route as PlanCareerRouteImport } from './routes/plan/career'
import { Route as AppSplatRouteImport } from './routes/app/$'
import { Route as ReviewIssuesKeyRouteImport } from './routes/review/issues/$key'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemIndexRoute = SystemIndexRouteImport.update({
  id: '/system/',
  path: '/system/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipIndexRoute = ShipIndexRouteImport.update({
  id: '/ship/',
  path: '/ship/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewIndexRoute = ReviewIndexRouteImport.update({
  id: '/review/',
  path: '/review/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanIndexRoute = PlanIndexRouteImport.update({
  id: '/plan/',
  path: '/plan/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObserveIndexRoute = ObserveIndexRouteImport.update({
  id: '/observe/',
  path: '/observe/',
  getParentRoute: () => rootRouteImport,
} as any)
const NowIndexRoute = NowIndexRouteImport.update({
  id: '/now/',
  path: '/now/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecuteIndexRoute = ExecuteIndexRouteImport.update({
  id: '/execute/',
  path: '/execute/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemSettingsRoute = SystemSettingsRouteImport.update({
  id: '/system/settings',
  path: '/system/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRegistryRoute = SystemRegistryRouteImport.update({
  id: '/system/registry',
  path: '/system/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemDocsRoute = SystemDocsRouteImport.update({
  id: '/system/docs',
  path: '/system/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanWeeklyRoute = PlanWeeklyRouteImport.update({
  id: '/plan/weekly',
  path: '/plan/weekly',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanQuarterlyRoute = PlanQuarterlyRouteImport.update({
  id: '/plan/quarterly',
  path: '/plan/quarterly',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanMonthlyRoute = PlanMonthlyRouteImport.update({
  id: '/plan/monthly',
  path: '/plan/monthly',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanCareerRoute = PlanCareerRouteImport.update({
  id: '/plan/career',
  path: '/plan/career',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/app/$',
  path: '/app/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewIssuesKeyRoute = ReviewIssuesKeyRouteImport.update({
  id: '/review/issues/$key',
  path: '/review/issues/$key',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/$': typeof AppSplatRoute
  '/plan/career': typeof PlanCareerRoute
  '/plan/monthly': typeof PlanMonthlyRoute
  '/plan/quarterly': typeof PlanQuarterlyRoute
  '/plan/weekly': typeof PlanWeeklyRoute
  '/system/docs': typeof SystemDocsRoute
  '/system/registry': typeof SystemRegistryRoute
  '/system/settings': typeof SystemSettingsRoute
  '/agents/': typeof AgentsIndexRoute
  '/execute/': typeof ExecuteIndexRoute
  '/now/': typeof NowIndexRoute
  '/observe/': typeof ObserveIndexRoute
  '/plan/': typeof PlanIndexRoute
  '/review/': typeof ReviewIndexRoute
  '/ship/': typeof ShipIndexRoute
  '/system/': typeof SystemIndexRoute
  '/work/': typeof WorkIndexRoute
  '/review/issues/$key': typeof ReviewIssuesKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/$': typeof AppSplatRoute
  '/plan/career': typeof PlanCareerRoute
  '/plan/monthly': typeof PlanMonthlyRoute
  '/plan/quarterly': typeof PlanQuarterlyRoute
  '/plan/weekly': typeof PlanWeeklyRoute
  '/system/docs': typeof SystemDocsRoute
  '/system/registry': typeof SystemRegistryRoute
  '/system/settings': typeof SystemSettingsRoute
  '/agents': typeof AgentsIndexRoute
  '/execute': typeof ExecuteIndexRoute
  '/now': typeof NowIndexRoute
  '/observe': typeof ObserveIndexRoute
  '/plan': typeof PlanIndexRoute
  '/review': typeof ReviewIndexRoute
  '/ship': typeof ShipIndexRoute
  '/system': typeof SystemIndexRoute
  '/work': typeof WorkIndexRoute
  '/review/issues/$key': typeof ReviewIssuesKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/$': typeof AppSplatRoute
  '/plan/career': typeof PlanCareerRoute
  '/plan/monthly': typeof PlanMonthlyRoute
  '/plan/quarterly': typeof PlanQuarterlyRoute
  '/plan/weekly': typeof PlanWeeklyRoute
  '/system/docs': typeof SystemDocsRoute
  '/system/registry': typeof SystemRegistryRoute
  '/system/settings': typeof SystemSettingsRoute
  '/agents/': typeof AgentsIndexRoute
  '/execute/': typeof ExecuteIndexRoute
  '/now/': typeof NowIndexRoute
  '/observe/': typeof ObserveIndexRoute
  '/plan/': typeof PlanIndexRoute
  '/review/': typeof ReviewIndexRoute
  '/ship/': typeof ShipIndexRoute
  '/system/': typeof SystemIndexRoute
  '/work/': typeof WorkIndexRoute
  '/review/issues/$key': typeof ReviewIssuesKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/$'
    | '/plan/career'
    | '/plan/monthly'
    | '/plan/quarterly'
    | '/plan/weekly'
    | '/system/docs'
    | '/system/registry'
    | '/system/settings'
    | '/agents/'
    | '/execute/'
    | '/now/'
    | '/observe/'
    | '/plan/'
    | '/review/'
    | '/ship/'
    | '/system/'
    | '/work/'
    | '/review/issues/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/$'
    | '/plan/career'
    | '/plan/monthly'
    | '/plan/quarterly'
    | '/plan/weekly'
    | '/system/docs'
    | '/system/registry'
    | '/system/settings'
    | '/agents'
    | '/execute'
    | '/now'
    | '/observe'
    | '/plan'
    | '/review'
    | '/ship'
    | '/system'
    | '/work'
    | '/review/issues/$key'
  id:
    | '__root__'
    | '/'
    | '/app/$'
    | '/plan/career'
    | '/plan/monthly'
    | '/plan/quarterly'
    | '/plan/weekly'
    | '/system/docs'
    | '/system/registry'
    | '/system/settings'
    | '/agents/'
    | '/execute/'
    | '/now/'
    | '/observe/'
    | '/plan/'
    | '/review/'
    | '/ship/'
    | '/system/'
    | '/work/'
    | '/review/issues/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppSplatRoute: typeof AppSplatRoute
  PlanCareerRoute: typeof PlanCareerRoute
  PlanMonthlyRoute: typeof PlanMonthlyRoute
  PlanQuarterlyRoute: typeof PlanQuarterlyRoute
  PlanWeeklyRoute: typeof PlanWeeklyRoute
  SystemDocsRoute: typeof SystemDocsRoute
  SystemRegistryRoute: typeof SystemRegistryRoute
  SystemSettingsRoute: typeof SystemSettingsRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  ExecuteIndexRoute: typeof ExecuteIndexRoute
  NowIndexRoute: typeof NowIndexRoute
  ObserveIndexRoute: typeof ObserveIndexRoute
  PlanIndexRoute: typeof PlanIndexRoute
  ReviewIndexRoute: typeof ReviewIndexRoute
  ShipIndexRoute: typeof ShipIndexRoute
  SystemIndexRoute: typeof SystemIndexRoute
  WorkIndexRoute: typeof WorkIndexRoute
  ReviewIssuesKeyRoute: typeof ReviewIssuesKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/': {
      id: '/system/'
      path: '/system'
      fullPath: '/system/'
      preLoaderRoute: typeof SystemIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ship/': {
      id: '/ship/'
      path: '/ship'
      fullPath: '/ship/'
      preLoaderRoute: typeof ShipIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/': {
      id: '/review/'
      path: '/review'
      fullPath: '/review/'
      preLoaderRoute: typeof ReviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/': {
      id: '/plan/'
      path: '/plan'
      fullPath: '/plan/'
      preLoaderRoute: typeof PlanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observe/': {
      id: '/observe/'
      path: '/observe'
      fullPath: '/observe/'
      preLoaderRoute: typeof ObserveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/now/': {
      id: '/now/'
      path: '/now'
      fullPath: '/now/'
      preLoaderRoute: typeof NowIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/execute/': {
      id: '/execute/'
      path: '/execute'
      fullPath: '/execute/'
      preLoaderRoute: typeof ExecuteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/settings': {
      id: '/system/settings'
      path: '/system/settings'
      fullPath: '/system/settings'
      preLoaderRoute: typeof SystemSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/registry': {
      id: '/system/registry'
      path: '/system/registry'
      fullPath: '/system/registry'
      preLoaderRoute: typeof SystemRegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/docs': {
      id: '/system/docs'
      path: '/system/docs'
      fullPath: '/system/docs'
      preLoaderRoute: typeof SystemDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/weekly': {
      id: '/plan/weekly'
      path: '/plan/weekly'
      fullPath: '/plan/weekly'
      preLoaderRoute: typeof PlanWeeklyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/quarterly': {
      id: '/plan/quarterly'
      path: '/plan/quarterly'
      fullPath: '/plan/quarterly'
      preLoaderRoute: typeof PlanQuarterlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/monthly': {
      id: '/plan/monthly'
      path: '/plan/monthly'
      fullPath: '/plan/monthly'
      preLoaderRoute: typeof PlanMonthlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/career': {
      id: '/plan/career'
      path: '/plan/career'
      fullPath: '/plan/career'
      preLoaderRoute: typeof PlanCareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$': {
      id: '/app/$'
      path: '/app/$'
      fullPath: '/app/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/issues/$key': {
      id: '/review/issues/$key'
      path: '/review/issues/$key'
      fullPath: '/review/issues/$key'
      preLoaderRoute: typeof ReviewIssuesKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppSplatRoute: AppSplatRoute,
  PlanCareerRoute: PlanCareerRoute,
  PlanMonthlyRoute: PlanMonthlyRoute,
  PlanQuarterlyRoute: PlanQuarterlyRoute,
  PlanWeeklyRoute: PlanWeeklyRoute,
  SystemDocsRoute: SystemDocsRoute,
  SystemRegistryRoute: SystemRegistryRoute,
  SystemSettingsRoute: SystemSettingsRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  ExecuteIndexRoute: ExecuteIndexRoute,
  NowIndexRoute: NowIndexRoute,
  ObserveIndexRoute: ObserveIndexRoute,
  PlanIndexRoute: PlanIndexRoute,
  ReviewIndexRoute: ReviewIndexRoute,
  ShipIndexRoute: ShipIndexRoute,
  SystemIndexRoute: SystemIndexRoute,
  WorkIndexRoute: WorkIndexRoute,
  ReviewIssuesKeyRoute: ReviewIssuesKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
